name: supertextfield_padding_demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # super_editor: 
  #   git:
  #     url: https://github.com/iapicca/super_editor.git
  #     ref: supertextfield_padding
  #     path: super_editor
  super_editor: ^0.2.0
      
dependency_overrides:
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true